version: '3'
services:
  code-server:
    image: codercom/code-server:3.12.0
    ports:
      - "8080:8080"
    volumes:
      - ./.config:/home/coder/.config
      - ./project:/home/coder/project
    container_name: code_server_xv