version: '3'
services:
  mysql:
    image: mysql:5.7.32
    ports:
      - "3306:3306"
    # volumes:
    #   - ./data:/var/lib/mysql
    #   - ./mysql.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: Allen1234@
    networks:
      - backend
    # restart: always
    container_name: mysql_waimao
networks:
  frontend:
  backend: