version: '3'
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "82:80"
      - "84:82"
      - "86:84"
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx_logs:/var/log/nginx
      - ./ftp:/etc/ftp
      - ./html:/usr/share/nginx/html
    container_name: nginx_xv
networks:
  frontend:
  backend: