version: "3"
services:
  unpkg:
    image: dalongrong/unpkg:http-env
    environment:
      - "NPM_REGISTRY_URL=http://npm-registry:4873"
    ports:
      - "8080:8080"
  npm-registry:
    image: verdaccio/verdaccio:4
    restart: unless-stopped
    ports:
      - "4873:4873"
    container_name: verdaccio_xv
    volumes:
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/storage:/verdaccio/storage
      - ./verdaccio/plugins:/verdaccio/plugins
