version: '3'

services:
  db:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 111111
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
