version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    container_name: redis_waimao
    command: redis-server --port 6379 --requirepass redis --appendonly yes
networks:
  frontend:
  backend: